[Design] 로그인 화면 레이아웃 구성
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #10
Opened 2023-09-27 16:44 UTC by kybeen

## PR Checklist

아래 체크리스트를 확인하여 PR이 아래 항목들을 충족하는지 확인합니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [X] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [X] 추가/변경사항에 대한 테스트는 진행했나요?
- [X] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [ ] Feat: 새로운 기능을 추가
- [ ] Fix: 버그 수정
- [X] Design: CSS 등 사용자 UI 디자인 변경
- [ ] !BREAKING CHANGE: 커다란 API 변경의 경우
- [ ] !HOTFIX: 급하게 치명적인 버그를 고쳐야하는 경우
- [X] Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
- [ ] Refactor: 프로덕션 코드 리팩토링
- [ ] Comment: 필요한 주석 추가 및 변경
- [ ] Docs: 문서 수정
- [ ] Test: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음
- [ ] Chore: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
- [ ] Rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
- [ ] Remove: 파일을 삭제하는 작업만 수행한 경우

## What is the current behavior?

추가/변경사항에 대해 작성해주세요.
- 로그인 화면 기본적인 레이아웃을 구성해놨습니다.
  - 오토 레이아웃을 적용시켰습니다.
<img width="300" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/9808c4dd-33a8-4275-a93c-9b9a32641a3b">

- #7 에서 피드백 주신 들여쓰기, guard let 구문 수정 완료하였습니다.
- GoogleService-Info.plist 파일 경로 프로젝트 폴더 내부로 옮겨놓았습니다.

Issue Number: #3

Resolved: #

## Other information

뷰를 그린 경우 완성된 화면의 스크린샷을 같이 첨부해주세요.

- 로그인된 사용자는 앱을 열면 바로 메인 화면으로 진입하도록 하는 플로우에서
  - 사용자의 로그인 정보를 앱 상에 저장하려면 보안 측면에서 UserDefault 보다는 KeyChain이 낫지 않을까 싶습니다. 사용법을 잘 몰라서 추후 공부한 뒤에 해당 플로우를 적용시키는게 나을 것 같기도 한데 어떻게 생각하시나요?

(리뷰어는 사다리타기로 고름)

2023-09-28 03:43 UTC, zhunhe approved these changes
로그인뷰 레이아웃 수정 수고하셨습니다 ! 👍🏻👍🏻👍🏻

피그마를 확인해보니 Carmu 로고 이미 작성되어있는 것 같은데, 디자이너분들과 상의해서 확정이라면 에셋으로 가져와서 Xcode에 바로 반영해도 될 듯해요.

> ‼️로그인된 사용자는 앱을 열면 바로 메인 화면으로 진입하도록 하는 플로우에서
사용자의 로그인 정보를 앱 상에 저장하려면 보안 측면에서 UserDefault 보다는 KeyChain이 낫지 않을까 싶습니다. 사용법을 잘 몰라서 추후 공부한 뒤에 해당 플로우를 적용시키는게 나을 것 같기도 한데 어떻게 생각하시나요?

-> 이 부분은 적어주신 대로 추후 적용시켜도 문제 없다고 생각합니다. 저도 방법 같이 찾아볼게요 !

2023-09-28 03:43 UTC, zhunhe commented on Carmunication/Controllers/LoginViewController.swift
> +    fileprivate var currentNonce: String?
currentNonce 프로퍼티는 클래스 내부에서만 쓰이는 것 같은데 private가 더 적절하지 않을까요?
```suggestion
    private var currentNonce: String?
```

Swift 접근제어자에 대해 확인해보시는 것도 좋을 것 같아요!

2023-09-28 03:43 UTC, zhunhe commented on Carmunication/Controllers/LoginViewController.swift
>  class LoginViewController: UIViewController {
상속하지 않는 클래스에 대해서는 final 키워드를 사용하는 것을 권장합니다 !
```suggestion
final class LoginViewController: UIViewController {
```

2023-09-28 03:43 UTC, zhunhe commented on Carmunication/Controllers/LoginViewController.swift
> +    func setLoginViewLayout() {
변경된 메서드 이름이 더 직관적이고 좋네요 ! 👍🏻
해당 부분 애플 로그인 버튼을 제외하고 추후 View 모듈로 분리가 필요할 듯 합니다 :)

2023-09-28 04:18 UTC, kybeen commented on Carmunication/Controllers/LoginViewController.swift
> +    func setLoginViewLayout() {
SnapKit 적용 안했을 때 기준이긴 하지만 뷰 구성 코드가 꽤나 길어지더라구요ㅠ
View 모듈로 분리하는게 관리 측면에서 더 좋을 것 같습니다!

2023-09-28 04:27 UTC, kybeen commented on Carmunication/Controllers/LoginViewController.swift
> +    fileprivate var currentNonce: String?
파이어베이스 가이드를 보고 그대로 작성한 코드였는데 어차피 해당 변수 호출하는 함수가 다 같은 클래스에 있어서 private이 적절할 것 같네요!

2023-09-28 04:27 UTC, kybeen commented
수정사항 반영해서 커밋해놨습니다😃

2023-09-28 15:01 UTC, Taerogrammer requested changes

2023-09-28 15:01 UTC, Taerogrammer commented on Carmunication/Controllers/LoginViewController.swift
> +        NSLayoutConstraint.activate([
저는 레이아웃 관련 식은 클래스 안의 식이 너무 길어질 수도 있어서 extension에 빼서 메서드로 추가해놓는 방법으로 사용하는데, 혹시 참고해보셔도 좋을 것 같습니다! 

그리고 위처럼 작성한다면 하나의 NSLayoutConstraint.activate에 모든 값들을 추가해도 되지 않을까요,,? 
개행으로 나눠줘도 충분할 것 같은 느낌입니다!

2023-09-28 17:29 UTC, kybeen commented on Carmunication/Controllers/MyPage/MyPageViewController.swift
> +//        bottomView.backgroundColor = UIColor.white
엇...이거 다른 브랜치에서 작업하던건데 제가 실수로 커밋한 것 같습니다ㅠㅠ

2023-09-28 17:30 UTC, kybeen commented on Carmunication/Controllers/LoginViewController.swift
> +        NSLayoutConstraint.activate([
헉 그러게요 NSLayoutConstrain.activate를 나눌 필요가 없었군요🙃 수정해놓겠습니다!

2023-09-28 17:52 UTC, kybeen commented
피드백 반영해서 커밋했습니다!
Controllers > MyPage 폴더를 생성하고 기존의 MyProfileViewController.swift 파일을 MyPageViewController.swift로 변경하여 MyPage 폴더 안으로 옮겼습니다. 👉 원래 다른 브랜치에서 하려던 작업인데 실수로 해당 브랜치에서 작업하고 같이 커밋된 것 같습니다ㅠ

2023-09-29 12:23 UTC, Taerogrammer approved these changes
승인!

2023-09-29 12:24 UTC, merged