[Feat] 크루 생성 화면 Navigation 연결, SceneDelegate 분기 처리
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #179
Opened 2023-11-03 11:20 UTC by DhKimy

## PR Checklist

아래 체크리스트를 확인하여 PR이 아래 항목들을 충족하는지 확인합니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [x] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [x] 추가/변경사항에 대한 테스트는 진행했나요?
- [x] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [x] Feat: 새로운 기능을 추가

## What is the current behavior?

추가/변경사항에 대해 작성해주세요.

SceneDelegate에 isFirst 변수를 추가하고, 분기처리를 새로하여 화면이동 구현을 완료했습니다.
현재 데이터는 Firebase에 업로드 되지 않으며, 화면 이동만 구현된 상태입니다.
다음 작업에서 마지막 화면의 시작하기 버튼을 누르면 임의로 생성된 더미 데이터를 넣는 작업을 진행할 계획입니다.

작업 편의를 위해 SessionStartView 이후의 화면을 작업할 때는
SceneDelegate의 isFirst를 false로 변경해주시면 됩니다.

Issue Number: N/A

Resolved: #178 

## Other information

뷰를 그린 경우 완성된 화면의 스크린샷을 같이 첨부해주세요.

<운전자 화면 이동>
![Simulator Screen Recording - iPhone 15 - 2023-11-03 at 20 13 11](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/1a2b4477-eaf1-49b5-a77b-52a2e9f3631b)

<건너뛰기 이동>
![Simulator Screen Recording - iPhone 15 - 2023-11-03 at 20 15 00](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/42696f06-3046-4ad2-9688-edf9194bb4a5)

<동승자 화면 이동>
![Simulator Screen Recording - iPhone 15 - 2023-11-03 at 20 15 32](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/6fd7477a-7468-4b06-87b7-29ef806a2e51)

2023-11-03 13:58 UTC, Taerogrammer approved these changes
화면의 이동이 많은데, 고생하셨습니다 😇
LGTM

2023-11-03 15:10 UTC, kybeen requested changes
LGTM! 화면 전환 작업 수고하셨습니다👍

SnapKit 오토 레이아웃 제약조건 설정 시 `safeAreaLayoutGuide`에 대해 설정된 코드 중 `inset`이 아니라 `offset`으로 사용되고 있는 부분이 몇 군데 있는데 해당 부분 수정해주시면 감사하겠습니다!
파일이 많아서 모든 곳에 코멘트를 남기지는 않았는데 코멘트가 없는 부분도 `offset`이 사용되는 곳이 몇 개 있어서 확인 부탁드리겠습니다🙃

2023-11-03 15:10 UTC, kybeen commented on Carmu/Sources/Views/CrewMake/Driver/StopoverPointCheckView.swift
> +    lazy var noStopoverButton = LargeSelectButton(
혹시 `lazy var`로 바꾸신 특별한 이유가 있을까요?

저도 최근까지 습관적으로 다 `lazy var`로 UI 컴포넌트를 선언했는데, 관련 자료를 찾아보면
**_"다중 스레드에서 접근 시 한 번만 초기화되는 것이 보장되지 않는다."_**
라는 단점이 공통적으로 지적되더라구요. (야곰 스위프트 프로그래밍 책 202p에도 관련 내용이 있습니다!)

물론 당장 사용하는데는 문제가 없긴 하지만 항상 쓰는 것이 무조건 좋은 건 아닐 수도 있겠다는 생각이 들었습니다.🙃
저도 앞으로는 작업 시에 항상 필요한 UI 요소라면 그냥 `let` 키워드로 선언하고, 특정 이벤트 발생 시에만 나타나는 UI 요소라면 그 때 `lazy var`를 사용하도록 코드를 작성할 것 같아요.
(https://velog.io/@leedool3003/iOS-lazy-Variable)

해당 뷰에서 경유지 유무 버튼은 항상 있으니까 `let`으로 선언해도 되지 않을까 싶습니다!

2023-11-03 23:06 UTC, DhKimy commented
레이가 의견을 주신 코드리뷰 사항들 반영 완료했습니다.
lazy var... 잘 써야 겠군요.

2023-11-04 07:49 UTC, kybeen approved these changes

2023-11-04 07:49 UTC, merged