Bazzi/feat/#17 컬러 에셋, 폰트 에셋 추가
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #18
Opened 2023-10-01 06:19 UTC by DhKimy

## PR Checklist

- [x] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [x] 추가/변경사항에 대한 테스트는 진행했나요?
- [x] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [ ] Feat: 새로운 기능을 추가
- [ ] Design: CSS 등 사용자 UI 디자인 변경
- [ ] Comment: 필요한 주석 추가 및 변경없음

## What is the current behavior?
추가/변경사항에 대해 작성해주세요.

- 컬러 에셋을 추가하면서, UIFont에 관련된 에셋을 추가했습니다.
- SF-Pro를 쓸 수 있습니다.
- 컬러 에셋만 추가하려고 했지만, 폰트도 자주 쓰이며, 확정된 것들이 많기 때문에, extension으로 정리하여 쓸 수 있도록 했습니다.

```
UIColor.theme.red1
UIColor.semantic.accPrimary

let label1 = UILabel()
UIFont.CarmuFont.headline1.applyFont(label1)
```
이와 같은 식으로 사용이 가능합니다.

Issue Number: #17 

Resolved: #17 

## Other information

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/334ac5c0-3313-417e-912a-6ecc1ad9aac4">

2023-10-01 06:58 UTC, Taerogrammer approved these changes
고생하셨습니다~!

2023-10-01 12:34 UTC, zhunhe requested changes
컬러 에셋, 폰트 에셋 적용 수고하셨습니다! 👍🏻👍🏻👍🏻

UIFont+Extension.swift 파일에서 SwiftLint 관련 경고가 발생하고 있습니다 확인부탁드려요 !
그리고 UIColor+Extension.swift에 들어가 있는 구조체들도 따로 파일 분리가 필요해 보입니다 수정 부탁드릴게요 !

2023-10-01 12:34 UTC, zhunhe commented on Carmunication/Extensions/UIFont+Extension.swift
> +    }
SwiftLint 관련 경고가 나오고 있습니다 😅
아래처럼 수정해보시는건 어떨까요?
```suggestion
    enum CarmuFont {
        case subhead1, subhead2, subhead3
        case headline1, headline2
        case display1, display2, display3
        case body1, body1Long
        case body2, body2Long
        case body3, body3Long

        func applyFont(to label: UILabel) {
            let letterSpacing = -0.6// Letter spacing 조정

            guard let customFont = UIFont(name: fontName, size: fontSize) else {
                // 폰트를 찾을 수 없는 경우 기본 시스템 폰트 사용
                return
            }
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.lineHeightMultiple = lineHeight / fontSize
            let attributes: [NSAttributedString.Key: Any] = [
                .font: customFont,
                .kern: letterSpacing,
                .paragraphStyle: paragraphStyle
            ]
            label.attributedText = NSAttributedString(string: label.text ?? "", attributes: attributes)
        }

        private var fontName: String {
            switch self {
            case .subhead1, .subhead2, .subhead3, .headline1, .headline2, .display1, .display2, .display3:
                return "SFPro-Bold"
            case .body1, .body1Long, .body2, .body2Long, .body3, .body3Long:
                return "SFPro-Regular"
            }
        }

        private var fontSize: CGFloat {
            switch self {
            case .subhead1, .body1, .body1Long:
                return 12
            case .subhead2, .body2, .body2Long:
                return 14
            case .subhead3, .body3, .body3Long:
                return 16
            case .headline1:
                return 20
            case .headline2:
                return 24
            case .display1:
                return 28
            case .display2:
                return 32
            case .display3:
                return 36
            }
        }

        private var lineHeight: CGFloat {
            switch self {
            case .subhead1, .body1:
                return 12
            case .subhead2, .body2:
                return 14
            case .body1Long, .body2Long:
                return 18
            case .subhead3, .body3:
                return 22
            case .headline1, .body3Long:
                return 28
            case .headline2:
                return 34
            case .display1:
                return 38
            case .display2:
                return 42
            case .display3:
                return 46
            }
        }
    }
```

2023-10-01 12:34 UTC, zhunhe commented on Carmunication/Extensions/UIColor+Extension.swift
>  extension UIColor {
파일당 struct, class, enum 하나만 작성하는게 적절해 보여요!
코드를 작성하지 않은 다른 사람이 찾기 힘들 수도 있거든요

struct SemanticColor, struct ColorTheme는 파일을 따로 분리해보는건 어떨까요?

2023-10-01 14:18 UTC, DhKimy commented
수정 제안 사항을 모두 받아들여 변경시켜놓았습니다!

2023-10-01 19:25 UTC, kybeen commented
귀찮을 수 있는 작업인데 해주셔서 감사합니다🙇‍♂️

2023-10-02 01:23 UTC, zhunhe approved these changes
LGTM! 개행까지 잘 넣어주셨군요! 수고하셨습니다 👏🏻👏🏻👏🏻

2023-10-02 01:23 UTC, merged