[Feat] 메인 화면 구성하기
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #37
Opened 2023-10-09 17:16 UTC by Taerogrammer

## PR Checklist

아래 체크리스트를 확인하여 PR이 아래 항목들을 충족하는지 확인합니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [ ] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [ ] 추가/변경사항에 대한 테스트는 진행했나요?
- [ ] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [ ] Feat: 새로운 기능을 추가
- [ ] Fix: 버그 수정
- [ ] Design: CSS 등 사용자 UI 디자인 변경
- [ ] !BREAKING CHANGE: 커다란 API 변경의 경우
- [ ] !HOTFIX: 급하게 치명적인 버그를 고쳐야하는 경우
- [ ] Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
- [ ] Refactor: 프로덕션 코드 리팩토링
- [ ] Comment: 필요한 주석 추가 및 변경
- [ ] Docs: 문서 수정
- [ ] Test: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음
- [ ] Chore: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
- [ ] Rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
- [ ] Remove: 파일을 삭제하는 작업만 수행한 경우

## What is the current behavior?

추가/변경사항에 대해 작성해주세요.

- Views와 Controllers에 맞춰 컴포넌트들을 추가하였습니다.
- 가장 첫 번째 화면 레이아웃 설정, 폰트 및 색상 추가를 진행하였습니다.

Issue Number: #23 

Resolved: #23 

## Other information

뷰를 그린 경우 완성된 화면의 스크린샷을 같이 첨부해주세요.

- SE가 14에 비해 화면이 매우 작아서, 우선 padding 값을 통해 컴포넌트들을 조정하였는데, 나중에 디자이너분들이 보시고 좀 다른 방식을 원하신다면 수정할 예정입니다.

- 데이터 없을 때

[iPhone SE]

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/b51b94f4-6fb5-49a5-a373-cbc47737456e">

[iPhone 12 mini]

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/74eb9358-ea4a-41cd-bc33-6a068146047f">

[iPhone 14]

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/c28e9f12-2441-48f4-ba1e-47c30699130b">

- 데이터 있을 때

[iPhone SE]

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/f335d1a1-87ae-467b-a8f1-1a19883e641d">

[iPhone 12 mini]

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/3e6cef87-674b-4e95-aa89-f0b009910a12">

[iPhone 14]

<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/0a396d56-64ac-4bdf-b1b0-8745f2918a6e">

2023-10-09 22:14 UTC, DhKimy requested changes
구성 고생많으셨습니다.
다만, 코드가 너무 길어지면서 프로퍼티와 메서드가 제대로 분할이 안되어 있는 것 같은 느낌을 받았습니다.
조금 분할해보시고, 중간에 들어가는 날짜, 출발/도착지, 반복요일, 인원 정보가 표시되는 라벨의 경우 따로 분할해서 뷰를 구성하는 것이 더 나을 것 같다는 생각이 듭니다.
(모델을 집어넣을 때, 더 용이하게 넣을 수 있을 것 같아요)

UIColor, UIFont의 경우 일관성있게 static으로 선언된 theme, semantic, carmuFont로 바꾸어서 진행을 해주었으면 합니다.

추가적으로  xcscheme 같은 경우 올라와도 되는 파일인지 모르겠어서 추후 논의 후 PR 진행해야 할 것 같습니다.

한번 전체적으로 살펴보고 진행을 하도록 하십시다:)

2023-10-09 22:14 UTC, DhKimy commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +    }
이 부분은 따로 View를 분리하여 작성하는 것이 좋을 것 같습니다. 코드 길이가 전체적으로 길어지고 하니, 관리를 위해 분리를 해주는 것이 필요해보입니다.
마치 TableViewCell 처럼요!
가능하면, 화면 중앙 부분의 View를 따로 컴포넌트화 시키는 작업을 하면 좋을 것 같아요!

2023-10-09 22:14 UTC, DhKimy commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +                imageView.tintColor = SemanticColor().accPrimary
이미 저것들을 UIFont, UIColor에서 static으로 선언해 두었기 때문에 그렇게 쓰는것이 더 나을 것 같습니다.

2023-10-09 22:14 UTC, DhKimy commented on Carmunication/Views/SessionStart/SessionStartView.swift
>      let groupCollectionView: UICollectionView = {
가능하면, 프로퍼티를 화면에서 위에서 아래로 보이는 순서로 배치를 해주었으면 좋겠습니다!
상단 컬렉션뷰부터 시작해서, 그룹이름 -> 츨발도착지 -> 여정표시 -> 버튼 표시
이런 식으로요!

2023-10-09 22:14 UTC, DhKimy commented on Carmunication/Views/SessionStart/SessionStartView.swift
> +        label.textColor = UIColor.semantic.textBody
여기선 이렇게 썼네...

2023-10-10 00:06 UTC, Taerogrammer commented on Carmunication/Models/Font/CarmuFont.swift
> +    let body3 = UIFont(name: "SFPro-Regular", size: 22) ?? UIFont.systemFont(ofSize: 22)
엇 이거 22px로 되어있는 걸로 확인했었는데, 다시 수정하겠슴당

2023-10-10 00:06 UTC, Taerogrammer commented on Carmunication/Models/Font/CarmuFont.swift
> +    let body3 = UIFont(name: "SFPro-Regular", size: 22) ?? UIFont.systemFont(ofSize: 22)
엇 이거 22px로 되어있는 걸로 확인했었는데, 다시 수정하겠슴다

2023-10-10 00:08 UTC, Taerogrammer commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +                imageView.tintColor = SemanticColor().accPrimary
아아 넵넵 저렇게 수정하겠슴다

2023-10-10 00:12 UTC, Taerogrammer commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +
그러면 Date+Extension 파일로 추가해놓겠슴당

2023-10-10 00:20 UTC, Taerogrammer commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +        let dateLabel: UILabel = {
메서드 안에 있는 컴포넌트 같은 경우에는 값들이 변하지 않거나, 다른 뷰에서 연결시킬 필요가 없는 것들입니다. 모든 컴포넌트를 선언해놓게 되면 너무 많아지지 않을까,,, 싶어서 해당 뷰에서만 필요한 컴포넌트들을 안으로 넣어놨는데, setupUI와 setupConstraint으로 변경하겠습니다

2023-10-10 00:27 UTC, Taerogrammer commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +    }
addSubView와 같은 것들을 setupUI 메서드로 빼놓고 정리하겠슴다

2023-10-10 01:39 UTC, Taerogrammer commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +    }
아 원래 뷰를 분리하려고 했었는데, 나중에 데이터를 불러올 때 모델을 한 번만 호출하기 위해 같은 뷰에 적용하였습니다,,! 저희가 만드는 정도의 크기에서는 화면에 모델이 로딩되는 속도가 차이가 거의 안나겠지만, 뭔가 하나의 모델 정보를 통해 화면을 구성하는게 일관성이 있어보여서요!

2023-10-10 01:40 UTC, Taerogrammer commented on Carmunication/Views/SessionStart/SessionStartView.swift
>      let groupCollectionView: UICollectionView = {
흐음 해당 순서대로 진행하긴 했는데, 다시 한 번 확인해보겠습니다!

2023-10-10 01:41 UTC, Taerogrammer commented on Carmunication/Views/SessionStart/SessionStartView.swift
> +        label.textColor = UIColor.semantic.textBody
ㅋㅋㅋㅋㅋㅋㅋㅋ 쓰다가 Semantic() 뭐시기 이렇게 뜨길래 그렇게 만들었습니다,,, 수정하겠슴다

2023-10-10 01:57 UTC, zhunhe approved these changes
세션 시작하기 화면 구성 수고하셨습니다 !

iPhone SE, iPhone mini, iPhone 14 각각의 화면 꼼꼼하게 확인하셔서 작업하셨네요 ! 👍🏻

SnapKit으로 제약사항 적용하실 때 Superview를 기준으로 할 때는 `make.edges.equalToSuperview()`와 같은 형태로 작성하시는게 가독성면에서 더 좋을 것 같습니다!

모달 뷰 구현도 잘 부탁드릴게요 !

2023-10-10 01:57 UTC, zhunhe commented on Carmunication.xcodeproj/xcshareddata/xcschemes/Carmunication.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
xcshareddata같은 경우에는 github repo에 포함되어야 한다는 스택오버플로우 글이 있긴 하지만 내용확인해 보면 꼭 포함되어야 하는지 의문이긴 하네요 🤔 없어도 같은 동작을 한다면 삭제해도 되지 않을까 싶습니다

https://stackoverflow.com/questions/53034303/should-xcshareddata-be-checked-into-git-repo-for-xcode-project

2023-10-10 01:57 UTC, zhunhe commented on Carmunication/Controllers/SessionStart/SessionStartViewController.swift
>          return cell!
아래와 같은 형태로 사용하시면 forced unwrapping을 사용하지 않아도 될 것 같아요!

```swift
        guard let cell = sessionStartView.groupCollectionView.dequeueReusableCell(
            withReuseIdentifier: "groupCell",
            for: indexPath
        ) as? GroupCollectionViewCell else {
            return UICollectionViewCell()
        }
        cell.groupData = self.sessionStartView.groupData?[indexPath.row]
        return cell
```

2023-10-10 01:57 UTC, zhunhe commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +            make.centerY.equalTo(dayView)
superview를 기준으로 오토레이아웃을 잡는다면 아래와 같이 쓰는게 가독성이 좋을 것 같아요 😁

```suggestion
            make.leading.equalToSuperview().offset(12)
            make.centerY.equalToSuperview()
```

2023-10-10 01:57 UTC, zhunhe commented on Carmunication/Extensions/SessionStartView+Extension.swift
> +            make.centerX.centerY.equalTo(dayView)
요기두 마찬가지구요 😊

```suggestion
            make.center.equalToSuperview()
```

2023-10-10 01:57 UTC, zhunhe commented on Carmunication/Models/GroupData.swift
> +    var total: Int?          // 총 인원
모든 변수가 Optional이 아닐 것 같은데 반드시 있어야 하는 변수의 경우 Optional 해제하는 걸 고려하시는게 좋을 것 같습니다 !

2023-10-10 12:15 UTC, merged