[Feat] 유저 닉네임 수정 구현 & 회원탈퇴 로직 수정
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #65
Opened 2023-10-13 07:12 UTC by kybeen

## PR Checklist

아래 체크리스트를 확인하여 PR이 아래 항목들을 충족하는지 확인합니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [X] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [X] 추가/변경사항에 대한 테스트는 진행했나요?
- [X] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [X] Feat: 새로운 기능을 추가
- [X] Fix: 버그 수정
- [ ] Design: CSS 등 사용자 UI 디자인 변경
- [ ] !BREAKING CHANGE: 커다란 API 변경의 경우
- [ ] !HOTFIX: 급하게 치명적인 버그를 고쳐야하는 경우
- [ ] Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
- [ ] Refactor: 프로덕션 코드 리팩토링
- [ ] Comment: 필요한 주석 추가 및 변경
- [ ] Docs: 문서 수정
- [ ] Test: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음
- [ ] Chore: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
- [ ] Rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
- [ ] Remove: 파일을 삭제하는 작업만 수행한 경우

## What is the current behavior?

추가/변경사항에 대해 작성해주세요.

Issue Number: #53

Resolved: #
- 프로필 사진 변경은 아직 구현X

## Other information

뷰를 그린 경우 완성된 화면의 스크린샷을 같이 첨부해주세요.

### 로그인 인증 시 사용자 닉네임 값 저장 로직 구현
- 사용자 정보 DB 저장 과정을 더 세분화해서 닉네임 저장 로직을 구현했습니다.
  - DB 상에 등록된 nickname 값이 있으면 유저 UPDATE
  - 등록된 nickname 값이 없으면 기본 `displayName`으로 nickname 초기값을 설정해서 유저 CREATE
<img width="481" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/4921c145-a9ae-470c-bf2e-6e7669c0d869">

### 닉네임 정보 수정 기능 구현
- 내 정보 페이지에서 유저 닉네임 수정 시 DB에 반영되도록 했습니다.
- 내 정보 페이지를 불러올 때 DB에서 유저 닉네임을 불러오도록 했습니다.
  - ‼️네트워크 통신으로 불러오기 때문에 내 정보 페이지를 처음 불러올 때 약간의 딜레이가 있습니다. 해당 부분을 어떻게 개선하는게 좋을지에 대한 고민이 필요해 보입니다.   ex) 앱 최초 실행 시 유저 정보를 불러와서 앱 상에 캐싱하는 방식 등...)
<img width="300" alt="" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/c073ba0e-b426-48c7-8ecc-a9ad2c0b8114"><img width="628" alt="스크린샷 2023-10-13 오후 3 37 15" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/e9954fb2-b0b3-4fd8-9b38-df414ef75205">

### 회원탈퇴 시 오류 확인
- 이전에 #52 에서 작업해주신 회원탈퇴 시 DB 정보 삭제 코드에서 아래와 같은 문제가 있었습니다.
  - `try await User.databasePathWithUID?.removeValue()`로 파이어베이스 DB의 유저 정보를 먼저 삭제하면 이후 Authentication의 계정은 삭제되지 않는 문제가 있었습니다. ( `try await user?.delete()`가 제대로 수행되지 않음. )

👉 코드 실행 순서를 변경하니까 문제가 해결되긴 했는데 정확히 어떤 이유로 문제가 있었던 건지는 아직 모르겠습니다🥲
- `try await User.databasePathWithUID?.removeValue()`는 Realtime Database DB 상에 별도로 저장된 유저 정보를 삭제하기 때문에, Authentication에 저장된 유저 정보를 삭제하는 `try await user?.delete()`코드에 영향을 미칠 이유가 없지 않나 생각됩니다...만 실제 동작은 그렇지 않은 것 같습니다. 혹시 원인을 아실 것 같은 분이 계시다면 의견을 남겨주시면 감사하겠습니다..!

- 문제의 코드
<img width="563" alt="스크린샷 2023-10-13 오후 3 45 17" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/fcdc8055-056a-498c-ae71-f3c035ad7a4a">

- 수정된 코드 (실행 순서 변경)
<img width="564" alt="스크린샷 2023-10-13 오후 4 07 35" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/8bc5b2db-ba57-46c0-8292-39e7a7ae3489">

2023-10-13 07:21 UTC, Taerogrammer reviewed
고생하셨습니다 ! 😇
다만 메서드 정의를 할 때 해당 클래스에서만 사용하신다면 private을 붙여놔주세요 !!!!
(다른 클래스에서 불러와지거나 메서드명이 같으면 중복으로 정의했다라는 등의 에러가 나타날 수도 있을 것 같습니다.)

2023-10-13 07:21 UTC, Taerogrammer commented on Carmunication/Controllers/MyPage/MyPageViewController.swift
>      @objc func showSettings() {
@objc 메서드도 private으로도 해주십쇼 !

2023-10-13 07:26 UTC, kybeen commented
> 고생하셨습니다 ! 😇
> 다만 메서드 정의를 할 때 해당 클래스에서만 사용하신다면 private을 붙여놔주세요 !!!!
> (다른 클래스에서 불러와지거나 메서드명이 같으면 중복으로 정의했다라는 등의 에러가 나타날 수도 있을 것 같습니다.)

수정했습니다!🤡

2023-10-13 12:34 UTC, zhunhe requested changes
닉네임 수정시 DB에 업데이트하는 작업 수고하셨습니다 !

이전 작업을 포함해서 옵셔널 해제 방법으로 강제 추출을 자주 사용하고 계시는데 지양해야하지 않을까하는 생각이 듭니다.
if문으로 nil이 아님을 확인하면 크래시가 발생하진 않겠지만, Swift 문법적으로 옵셔널 바인딩이라는 방법이 있거든요. 😅

회원탈퇴 후 로그인화면으로 이동하지 않는 현상은 #52 가 머지되기 이전에 develop 브랜치에서도 발생하는 현상이었는데요, 꼭 이번 PR에 포함시키지 않더라도 원인이 제대로 분석된 상태에서 수정을 해야하지 않을까 조심히 의견을 전달해봅니다.

2023-10-13 16:36 UTC, kybeen commented on Carmunication/Controllers/LoginViewController.swift
> +            }
설명이 굉장히 잘돼있네요.. 옵셔널 시리즈 모두 정독했습니다:)

파이어베이스 공식 문서의 코드를 그대로 활용했는데 어차피 nil값이 아님은 보장돼서 문제 없을거라 생각했습니다. 그러다보니 경각심이 덜해진 것 같기도 하네요... 최대한 지양하도록 신경을 많이 써보겠습니다🥲

2023-10-13 16:40 UTC, Taerogrammer commented on Carmunication/Controllers/LoginViewController.swift
> +            }
무슨 시리즈를 정독하신건가요 ㅋㅋ?

2023-10-13 19:18 UTC, kybeen commented on Carmunication/Controllers/LoginViewController.swift
> +            }
> 무슨 시리즈를 정독하신건가요 ㅋㅋ?

https://babbab2.tistory.com/16 여기 옵셔널 시리즈 정독했습니다 ㅋㅋ 나중에 시간 되면 읽어보시길... 설명 잘해주시네요

2023-10-13 19:25 UTC, kybeen commented
> 닉네임 수정시 DB에 업데이트하는 작업 수고하셨습니다 !
> 
> 이전 작업을 포함해서 옵셔널 해제 방법으로 강제 추출을 자주 사용하고 계시는데 지양해야하지 않을까하는 생각이 듭니다. if문으로 nil이 아님을 확인하면 크래시가 발생하진 않겠지만, Swift 문법적으로 옵셔널 바인딩이라는 방법이 있거든요. 😅
> 
> 회원탈퇴 후 로그인화면으로 이동하지 않는 현상은 #52 가 머지되기 이전에 develop 브랜치에서도 발생하는 현상이었는데요, 꼭 이번 PR에 포함시키지 않더라도 원인이 제대로 분석된 상태에서 수정을 해야하지 않을까 조심히 의견을 전달해봅니다.

원인 분석하고 해결했습니다!

내용이 길어 노션에 정리했습니다 👉 https://www.notion.so/2a2ebac14833401eb71cc131ac19a0e0?pvs=4

결론적으로 회원 탈퇴 시 코드는 문제가 없었고 삭제 로직 자체도 정상적으로 잘 수행되고 있었습니다.

`User.databasePathWithUID` 값이 `KeychainItem.currentUserIdentifier` 값이 바뀔 때 같이 갱신이 되지 않아 DB에 접근하는 경로가 잘못되고 있었던 것이 진짜 원인이었습니다. (#67)
값이 갱신되도록 코드 수정해서 말씀하신 수정 요청사항과 함께 반영해놨습니다:)

2023-10-14 05:49 UTC, zhunhe approved these changes
결국 static let으로 선언된 변수가 문제였군요. 원인 분석 및 수정 감사드립니다 🙇🏻‍♂️

2023-10-14 05:52 UTC, DhKimy commented
닉네임 등 회원정보는 앱 상의 어디엔가 저장하기에는 보안상 좋지 않은 방법인 것 같습니다.
이를 해결하기 위해 화면의 비동기 처리 등으로 화면을 구현하는 것이 더 좋은 방법일듯합니다.
수고 많으셨읍니다.

2023-10-14 05:54 UTC, DhKimy approved these changes

2023-10-14 05:54 UTC, merged