[feat] 애플 로그인 관련 세팅 및 구현
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #7
Opened 2023-09-25 14:16 UTC by kybeen

## PR Checklist

아래 체크리스트를 확인하여 PR이 아래 항목들을 충족하는지 확인합니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [X] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [X] 추가/변경사항에 대한 테스트는 진행했나요?
- [X] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [X] Feat: 새로운 기능을 추가
- [ ] Fix: 버그 수정
- [ ] Design: CSS 등 사용자 UI 디자인 변경
- [ ] !BREAKING CHANGE: 커다란 API 변경의 경우
- [ ] !HOTFIX: 급하게 치명적인 버그를 고쳐야하는 경우
- [ ] Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
- [ ] Refactor: 프로덕션 코드 리팩토링
- [ ] Comment: 필요한 주석 추가 및 변경
- [ ] Docs: 문서 수정
- [ ] Test: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음
- [ ] Chore: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
- [ ] Rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
- [ ] Remove: 파일을 삭제하는 작업만 수행한 경우

## What is the current behavior?

추가/변경사항에 대해 작성해주세요.
- 애플 로그인 관련 세팅 진행
  - 파이어베이스 연동, 패키지 설치
  - Sign In with Apple capability 추가
  - 프로비저닝, Bundle ID 세팅
- 애플 로그인 구현
<img width="300" alt="선택" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/a8e0f92e-d592-44be-9f69-ba077dad1cc6">

Issue Number: #3

## Other information

2023-09-26 10:17 UTC, zhunhe approved these changes
애플 로그인 구현 수고하셨습니다 ! 👍🏻👍🏻👍🏻

파이어베이스 키 값 관련 파일 .gitignore에 추가해두신 것 잘봤습니다.
추후 GoogleService-Info.plist 파일도 공유 부탁드릴게요 !

꼼꼼하게 코드 작성해주셨지만 중간중간 들여쓰기가 2칸으로 되어있는 코드가 있어서 아쉬웠습니다.

그리고 상속하지 않는 class의 경우 final 키워드를 붙여주면 성능 최적화가 이뤄지니 참고하셔도 좋을 것 같아요!
https://jcsoohwancho.github.io/2019-10-11-Dynamic-Dispatch%EC%99%80-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94

2023-09-26 10:17 UTC, zhunhe commented on Carmunication/Controllers/LoginViewController.swift
> +    }
여기도 들여쓰기 4칸으로 부탁드릴게요 !

2023-09-26 10:17 UTC, zhunhe commented on Carmunication/Controllers/LoginViewController.swift
> +        if let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential {
이 부분 if 보다는 guard 쓰는건 어떨까요?

2023-09-27 01:38 UTC, DhKimy requested changes
Firebase 관련된 초기화 부분 주석만 좀 부탁드리겠읍니다.
SnapKit 도입하여 앞으로 개발 진행을 해야 할 것 같습니다.
수고하셨네용!

2023-09-27 01:38 UTC, DhKimy commented on Carmunication/Controllers/LoginViewController.swift
> +fileprivate var currentNonce: String?
이 부분은 어떤 역할을 하는 걸까요

2023-09-27 01:38 UTC, DhKimy commented on Carmunication/Controllers/LoginViewController.swift
> +            appleSignInButton.centerXAnchor.constraint(equalTo: view.centerXAnchor),
하루 빨리 SnapKit을 도입해야 할 것 같습니다.

2023-09-27 01:38 UTC, DhKimy commented on Carmunication/Controllers/LoginViewController.swift
> +        if let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential {
공감하는 바입니다

2023-09-27 01:38 UTC, DhKimy commented on Carmunication/Controllers/LoginViewController.swift
> +            let credential = OAuthProvider.appleCredential(withIDToken: idTokenString,
요 부분 시작하는 것부터 로직 흐름을 간략하게 주석달아줄 수 있나요??
Firebase 초기화 부분이라 자세히 알아야 할 거 같습니다.

2023-09-27 01:38 UTC, DhKimy commented on Carmunication/Controllers/LoginViewController.swift
> +                let transition = CATransition()
Chat GPT를 잘 활용합시다

2023-09-27 03:25 UTC, Taerogrammer requested changes

2023-09-27 03:25 UTC, Taerogrammer commented on Carmunication/Controllers/LoginViewController.swift
> +            appleSignInButton.centerXAnchor.constraint(equalTo: view.centerXAnchor),
그리고 혹시 메서드 부분은 extension으로 빼놓는 것은 어떻게 생각하시나요?

기본 클래스 부분에서는 컴포넌트 설정과 메서드를 불러오는 등의 파일만 두고, 
extension에서 메서드를 관리하는 방법으로요!

2023-09-27 03:25 UTC, Taerogrammer commented on .github/pull_request_template.md
> +-->
- Resolved: #  도 넣어주실 수 있나요?
해당 문장을 작성하고, #이슈번호를 작성하면 해당 PR이 머지되었을 때 자동으로 이슈도 close 해줍니다!

<img width="300" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/85fadc46-fe78-4f1c-b764-f82842b7dcac">

2023-09-27 06:33 UTC, kybeen commented on Carmunication/Controllers/LoginViewController.swift
> +fileprivate var currentNonce: String?
애플 로그인 인증 시 호출되는 startSignInWithAppleFlow() 메서드 내부에서 아래 구문을 통해 랜덤한 임의의 문자열인 nonce 값을 생성하고, 이를 인증 요청 객체에 담아서 보냅니다. 이때 nonce의 값을 저장할 변수를 선언한 구문입니다.
( nonce : 재전송 공격을 방지하기 위해 통신 시 사용하는 암호화 임시 값 → 으로 알고 있습니다 )
<img width="653" alt="스크린샷 2023-09-27 오후 3 26 23" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/192b1280-d655-4510-8280-00f39be671d4">

( https://firebase.google.com/docs/auth/ios/apple?hl=ko 참고 )

2023-09-27 06:41 UTC, kybeen reviewed
불필요 주석 삭제 및 PR 템플릿에 Resolve 항목 추가했습니다!

2023-09-27 06:57 UTC, kybeen commented
> Firebase 관련된 초기화 부분 주석만 좀 부탁드리겠읍니다.
> SnapKit 도입하여 앞으로 개발 진행을 해야 할 것 같습니다.
> 수고하셨네용!

주석 추가해놨습니다! 아래 흐름으로 생각하시면 될 것 같아요
- **애플 인증(로그인) 성공 시** authorizationController(controller:didCompleteWithAuthorization:) 메소드 호출
- authorizationController(controller:didCompleteWithAuthorization:) 메소드의 인자값을 가지고 **파이어베이스 2차 인증**

👉 [애플 인증] → [파이어베이스 인증] 까지 모두 성공하고 나면 로그인 성공 동작이 처리됩니다.

2023-09-27 06:59 UTC, kybeen commented
요청하신 수정사항 어느 정도 반영해놨고, 들여쓰기랑 문법적인 부분 등 코드 관련 작업은 이후 작업에서 같이 반영해놓겠습니다 !

2023-09-27 09:01 UTC, Taerogrammer approved these changes
굳 ㅋㅋ~!

2023-09-27 09:43 UTC, DhKimy approved these changes

2023-09-27 09:44 UTC, merged