[Design] 세션 시작하기 레이아웃 설정
DeveloperAcademy-POSTECH/MacC-Team-DGC pull request #9
Opened 2023-09-27 07:57 UTC by Taerogrammer

## PR Checklist

아래 체크리스트를 확인하여 PR이 아래 항목들을 충족하는지 확인합니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [ ] 팀원들과 약속한 커밋메세지 룰을 지켜서 작성했나요?
- [ ] 추가/변경사항에 대한 테스트는 진행했나요?
- [ ] 추가/변경사항에 대한 문서는 수정했나요?

## PR Type

어떤 변경사항이 있는지 PR에 해당하는 작업들을 체크해줍니다. **(편집기 상에서는 [X] 표시하면 체크됩니다.)**

- [ ] Feat: 새로운 기능을 추가
- [ ] Fix: 버그 수정
- [ ] Design: CSS 등 사용자 UI 디자인 변경
- [ ] !BREAKING CHANGE: 커다란 API 변경의 경우
- [ ] !HOTFIX: 급하게 치명적인 버그를 고쳐야하는 경우
- [ ] Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
- [ ] Refactor: 프로덕션 코드 리팩토링
- [ ] Comment: 필요한 주석 추가 및 변경
- [ ] Docs: 문서 수정
- [ ] Test: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음
- [ ] Chore: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
- [ ] Rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
- [ ] Remove: 파일을 삭제하는 작업만 수행한 경우

## What is the current behavior?

- 그룹 셀 생성
- 여행 시작하기 버튼 생성 및 클릭 시 모달창 띄우기
- 모달창에서 버튼 클릭 시 세션 시작 뷰로 이동

Issue Number: #6 

## Other information

궁금한 것이 있습니다!

- 폴더링은 어떻게 관리할 것인가요?
제가 해본 방식은 탭바 별로 폴더링 -> 화면을 기준으로 폴더 생성 후 Model, View, Controller 폴더 생성과 같이 진행하였는데, 다른 좋은 방법이 있을까요?! 

- 우선 모달창에서 세션 시작 중 화면으로 넘어가는 것을 할 때 full-screen으로 올리는 것이 좋을 것 같다는 의견이 있어서 그렇게 만들어놓았는데, 혹시 제가 제대로 이해했는지 영상에서 확인해주시면 감사하겠습니다 ^_^

https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/ace51a70-db95-48bd-b8fd-9f25bf483536

2023-09-27 12:41 UTC, zhunhe requested changes
세션 시작하기 화면 구성 수고하셨습니다 !! 🥳🥳🥳

작성해주신 코드와 커밋 메시지를 확인해봤는데요,
커밋 메시지를 더 명확하게 작성해주시면 좋겠다는 아쉬움이 있었습니다.
예를 들어 아래와 같은 메시지는 SwiftLint를 프로젝트에 적용했다는 의미를 담고 있는데 실제 수정사항을 확인해보니 SwiftLint 경고 메시지에 관한 코드 내용을 수정한 커밋이더라구요.
[chore] #6 - SwiftLint 적용
위의 메시지보다는 "[refactor] #6 - SwiftLint 경고 관련 코드 수정" 이나 [refactor] #6 - SwiftLint 관련 수정" 으로 작성하는게 명확하게 의미전달이 되지 않을까 싶습니다.

위와 관련해서 notion에 정리되어있는 commit convention, 특히 prefix 부분 다시 한 번 확인 부탁드릴게요!
https://www.notion.so/15fc24ca5fdd47f8a32799c672ccf167?pvs=4

다음은 질문 주셨던 부분에 대한 답변입니다.

Q) 폴더링은 어떻게 관리할 것인가요?
-> 개발회의 때 얘기나왔던 부분인데요, 탭바별로 관리하지 않고 Model, View, Controller로 분리한 후 그 안에서 연관되는 파일별로 묶는 방식으로 진행하자고 나왔던 기억이 있습니다. 탭바별로 묶어버리면 재사용되는 화면을 관리하기가 힘들어질 것 같아요.

Q) 우선 모달창에서 세션 시작 중 화면으로 넘어가는 것을 할 때 full-screen으로 올리는 것이 좋을 것 같다는 의견이 있어서 그렇게 만들어놓았는데, 혹시 제가 제대로 이해했는지 영상에서 확인해주시면 감사하겠습니다 ^_^
-> 만들어주신대로 modal로 처리해도 문제 없을 듯 합니다. :)

코멘트들 아래 남겨두었으니 확인 부탁드릴게요 !
SwiftLint가 제대로 설정되어있다면 경고 메세지가 떴을 것 같은데, 제대로 동작하고 있지 않은 것으로 보이니 확인부탁드립니다 !

SwiftLint 관련 부분들은 다시 설정 후에 경고 메시지가 뜨지 않도록 수정 부탁드릴게요 !

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStartViewController.swift
> +extension SessionStartViewController {
해당 모듈은 extension으로 분리해야할 이유가 있을까요?

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStartViewController.swift
> +                    as? GroupCollectionViewCell
120자 제한으로 인해 개행해주신 것 같은데 조금 더 가독성을 신경써주시면 좋을 것 같아요 !

```suggestion
        let cell = groupCollectionView.dequeueReusableCell(
            withReuseIdentifier: "groupCell",
            for: indexPath
        ) as? GroupCollectionViewCell
```

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStart/SessionMapViewController.swift
> +class SessionMapViewController: UIViewController {
여기도 마찬가지로 final 클래스 붙여주는게 좋아보입니다!

```suggestion
final class SessionMapViewController: UIViewController {
```

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +extension GroupCollectionViewCell {
모듈 사이에는 개행으로 분리해주는게 가독성이 좋아요!

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStartViewController.swift
> +                  total: 4),
마지막 parameter에는 ,를 사용하지 않아요!
```suggestion
                  total: 4)
```

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStartViewController.swift
> +        GroupData(image: UIImage(systemName: "square")!,
불필요한 공백은 삭제해주세요! SwiftLint에서 경고 메세지가 안떴다면 제대로 설정되어있는지 다시 확인부탁드립니다
```suggestion
        GroupData(image: UIImage(systemName: "heart")!,
                  groupName: "group1",
                  start: "양덕",
                  end: "C5",
                  startTime: "08:30",
                  endTime: "9:00",
                  date: "주중(월 - 금)",
                  total: 4),
        GroupData(image: UIImage(systemName: "circle")!,
                  groupName: "group2",
                  start: "포항",
                  end: "부산",
                  startTime: "08:30",
                  endTime: "9:00",
                  date: "주중(월 - 금)",
                  total: 4),
        GroupData(image: UIImage(systemName: "heart.fill")!,
                  groupName: "group3",
                  start: "인천",
                  end: "서울",
                  startTime: "08:30",
                  endTime: "9:00",
                  date: "주중(월 - 금)",
                  total: 4),
        GroupData(image: UIImage(systemName: "circle.fill")!,
                  groupName: "group4",
                  start: "부평",
                  end: "일산",
                  startTime: "08:30",
                  endTime: "9:00",
                  date: "주중(월 - 금)",
                  total: 4),
        GroupData(image: UIImage(systemName: "square")!,
```

2023-09-27 12:41 UTC, zhunhe commented on Carmunication/Controllers/SessionStartViewController.swift
> +                    sizeForItemAt indexPath: IndexPath) -> CGSize {
SwiftLint에서 경고 메시지 출력되고 있는데 확인해주세요 !
```suggestion
    func collectionView(
        _ collectionView: UICollectionView,
        layout collectionViewLayout: UICollectionViewLayout,
        sizeForItemAt indexPath: IndexPath
    ) -> CGSize {
```

2023-09-27 13:05 UTC, Taerogrammer commented
> 세션 시작하기 화면 구성 수고하셨습니다 !! 🥳🥳🥳
> 
> 작성해주신 코드와 커밋 메시지를 확인해봤는데요, 커밋 메시지를 더 명확하게 작성해주시면 좋겠다는 아쉬움이 있었습니다. 예를 들어 아래와 같은 메시지는 SwiftLint를 프로젝트에 적용했다는 의미를 담고 있는데 실제 수정사항을 확인해보니 SwiftLint 경고 메시지에 관한 코드 내용을 수정한 커밋이더라구요. `[chore] #6 - SwiftLint 적용` 위의 메시지보다는 "[refactor] #6 - SwiftLint 경고 관련 코드 수정" 이나 "[refactor] #6 - SwiftLint 관련 수정" 으로 작성하는게 명확하게 의미전달이 되지 않을까 싶습니다.
> 
> 위와 관련해서 notion에 정리되어있는 commit convention, 특히 prefix 부분 다시 한 번 확인 부탁드릴게요! https://www.notion.so/15fc24ca5fdd47f8a32799c672ccf167?pvs=4
> 
> 다음은 질문 주셨던 부분에 대한 답변입니다.
> 
> > Q) 폴더링은 어떻게 관리할 것인가요?
> 
> -> 개발회의 때 얘기나왔던 부분인데요, 탭바별로 관리하지 않고 Model, View, Controller로 분리한 후 그 안에서 연관되는 파일별로 묶는 방식으로 진행하자고 나왔던 기억이 있습니다. 탭바별로 묶어버리면 재사용되는 화면을 관리하기가 힘들어질 것 같아요.
> 
> > Q) 우선 모달창에서 세션 시작 중 화면으로 넘어가는 것을 할 때 full-screen으로 올리는 것이 좋을 것 같다는 의견이 있어서 그렇게 만들어놓았는데, 혹시 제가 제대로 이해했는지 영상에서 확인해주시면 감사하겠습니다 ^_^
> 
> -> 만들어주신대로 modal로 처리해도 문제 없을 듯 합니다. :)
> 
> 코멘트들 아래 남겨두었으니 확인 부탁드릴게요 ! SwiftLint가 제대로 설정되어있다면 경고 메세지가 떴을 것 같은데, 제대로 동작하고 있지 않은 것으로 보이니 확인부탁드립니다 !
> 
> SwiftLint 관련 부분들은 다시 설정 후에 경고 메시지가 뜨지 않도록 수정 부탁드릴게요 !

자세한 피드백 감사합니다 ㅎㅎ!!
코멘트들은 해당 코멘트에 답변 남기겠습니다~!

2023-09-27 14:55 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +class GroupCollectionViewCell: UICollectionViewCell {
넵 final 추가하겠슴다!

2023-09-27 14:56 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +    required init?(coder: NSCoder) {
아 처음에 구분했는데, swiftLint에서 그 노란줄로 뜨더라고여,,,? 그래서 이것도 붙여야되는 건지 알았습니다,,!
그럼 개행으로 띄워놓겠습니다~!

2023-09-27 14:56 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +    fileprivate let groupImage: UIImageView = {
넵 공부해봐야겠군여 ㅋㅋㅋ

2023-09-27 14:57 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStart/ModalQueueViewController.swift
> +class ModalQueueViewController: UIViewController {
아아 넵 추가하겠슴다!

2023-09-27 14:57 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +extension GroupCollectionViewCell {
넵!

2023-09-27 14:57 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +                  total: 4),
아앗 이건 제 오타,,, 수정하겠슴다!

2023-09-27 14:58 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +        GroupData(image: UIImage(systemName: "square")!,
아 이게 그 한줄로 썼을 때 그 줄 길이가 길면 안된다는 노란 문구가 떠서 이렇게 변경하였습니다!
그냥 한 줄로 작성할까요?

2023-09-27 14:59 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +                    sizeForItemAt indexPath: IndexPath) -> CGSize {
아아 넵 수정하겠슴다!

2023-09-27 15:19 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +extension SessionStartViewController {
평소에 작업할 때 해당 class에는 프로퍼티만 생성해두고, 메서드들을 extension으로 분리하여 작업하는 방식으로 진행했어서 그렇습니다!

2023-09-27 15:19 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +                    as? GroupCollectionViewCell
넵 어떻게 개행해줘야 될 지 몰라서 이렇게했었습니다 ㅋㅋㅋ!! 참고하겠습니다!

2023-09-27 15:22 UTC, DhKimy approved these changes
SnapKit을 도입합시다

2023-09-27 15:22 UTC, DhKimy commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +    required init?(coder: NSCoder) {
개행으로 띄워놓는게 노란줄로 뜨긴하는데, MARK 주석이나 다른 것들로 구분을 해놓아도 좋지 않을까요..?
(ex. 클래스 내부에서 변수 - 메서드 사이 / 주요 기능 메서드 - 초기화 메서드 사이)

2023-09-27 15:22 UTC, DhKimy commented on Carmunication/Controllers/SessionStartViewController.swift
> +        GroupData(image: UIImage(systemName: "circle")!,
나중에는 
GroupData(
    image: ~~~

)
로 쓰는 것 잊지말아요~

2023-09-27 15:23 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +        GroupData(image: UIImage(systemName: "heart")!,
오호 알겠슴당 ㅎㅎㅋㅎㅎ

2023-09-27 15:27 UTC, zhunhe commented on Carmunication/Controllers/SessionStartViewController.swift
> +        GroupData(image: UIImage(systemName: "square")!,
SwiftLint에서 trailing whilespace 관련 경고 메시지가 나왔을거에요 ! 한 줄로 작성하느냐 나눠서 작성하느냐의 선택이 아니라 space로 끝나는게 문제입니다 !

2023-09-28 00:52 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
> +    required init?(coder: NSCoder) {
> 개행으로 띄워놓는게 노란줄로 뜨긴하는데, MARK 주석이나 다른 것들로 구분을 해놓아도 좋지 않을까요..? (ex. 클래스 내부에서 변수 - 메서드 사이 / 주요 기능 메서드 - 초기화 메서드 사이)

아아 그럼 MARK 주석도 좋은 것 같은데 MARK로 구분을 해놓을까요?!

2023-09-28 00:52 UTC, Taerogrammer commented on Carmunication/Controllers/SessionStartViewController.swift
> +        GroupData(image: UIImage(systemName: "square")!,
> SwiftLint에서 trailing whilespace 관련 경고 메시지가 나왔을거에요 ! 한 줄로 작성하느냐 나눠서 작성하느냐의 선택이 아니라 space로 끝나는게 문제입니다 !

아아 어제 하면서 이해했습니다 ㅋㅋㅋㅋㅋ SwiftLint를 처음 써봐서 무엇이 정확한 원인이었는지 몰랐었던것 같슴다,,

2023-09-28 01:41 UTC, zhunhe commented
요기다 작성하시면 됩니다

2023-09-28 01:43 UTC, Taerogrammer commented
확인 한 번 부탁드리겠습니다~!

2023-09-28 03:28 UTC, zhunhe approved these changes

2023-09-28 03:29 UTC, merged